"""
Numerical parity between the PyTorch implementation and the former TensorFlow implementation.

The TensorFlow reference outputs in ``data/tf_reference.npz`` were generated by ``gen_tf_reference.py``
from the last TensorFlow-based commit. Run from the project root with:

    pytest tests -v
"""

import sys
from pathlib import Path

import numpy as np
import pytest
import torch

sys.path.insert(0, str(Path(__file__).parent))
import cases  # noqa: E402
from cissir import adc, beamforming as bf, raytracing as rtr  # noqa: E402
from cissir.sigproc import signal_power  # noqa: E402
from cissir.utils import axes_tuple  # noqa: E402

REF_PATH = Path(__file__).parent/"data"/"tf_reference.npz"

# Relative tolerance in terms of the largest magnitude of the reference (single precision)
RTOL32 = 2e-6
RTOL64 = 1e-12


@pytest.fixture(scope="module")
def ref():
    with np.load(REF_PATH) as d:
        return {k: d[k] for k in d.files}


def assert_close(actual, expected, rtol, name=""):
    actual = actual.detach().cpu().numpy() if isinstance(actual, torch.Tensor) else np.asarray(actual)
    assert actual.shape == expected.shape, f"{name}: shape {actual.shape} != {expected.shape}"
    assert actual.dtype == expected.dtype, f"{name}: dtype {actual.dtype} != {expected.dtype}"
    scale = max(np.max(np.abs(expected)), np.finfo(np.float32).tiny)
    err = np.max(np.abs(actual - expected))
    assert err <= rtol * scale, f"{name}: max abs error {err:.3e} > {rtol * scale:.3e} (scale {scale:.3e})"


def assert_equal(actual, expected, name=""):
    actual = actual.detach().cpu().numpy() if isinstance(actual, torch.Tensor) else np.asarray(actual)
    assert actual.shape == expected.shape, f"{name}: shape {actual.shape} != {expected.shape}"
    np.testing.assert_array_equal(actual, expected, err_msg=name)


# ---------------------------------------------------------------------------------------------
# utils
# ---------------------------------------------------------------------------------------------

def test_axes_tuple():
    assert axes_tuple(None, 3) == (0, 1, 2)
    assert axes_tuple(-1, 4) == (3,)
    assert axes_tuple((2, -4, 2), 4) == (0, 2)
    with pytest.raises(ValueError):
        axes_tuple(3, 3)


# ---------------------------------------------------------------------------------------------
# beamforming
# ---------------------------------------------------------------------------------------------

@pytest.mark.parametrize("name", cases.CHANNEL_POWER_KWARGS)
def test_signal_power_sum(ref, name):
    """Default behavior (sum over axes) against TF ``channel_power`` (moved from beamforming)"""
    out = signal_power(torch.from_numpy(cases.channel_power_input()), **cases.CHANNEL_POWER_KWARGS[name])
    assert_close(out, ref[f"channel_power/{name}"], RTOL32, name)


@pytest.mark.parametrize("name", cases.BEAM_SELECTION_CASES)
def test_beam_selection(ref, name):
    case = cases.BEAM_SELECTION_CASES[name]
    h = cases.beam_selection_input(case)
    out = bf.BeamSelection(**case["kwargs"])(torch.from_numpy(h))
    expected = ref[f"beam_selection/{name}"]
    if case["kwargs"].get("normalize", True):
        # Same selection, then an identical scaling
        assert_close(out, expected, RTOL32, name)
    else:
        # Pure selection: bitwise identical values, which also asserts identical tie-breaking
        assert_equal(out, expected, name)


@pytest.mark.parametrize("name", cases.beamspace_cases())
def test_beamspace(ref, name):
    case = cases.beamspace_cases()[name]
    double = case["h"].dtype == np.complex128
    layer = bf.Beamspace(transmit_axis=case["tx_axis"], receive_axis=case["rx_axis"],
                         precision="double" if double else None)
    inputs = [torch.from_numpy(case["h"])]
    inputs += [torch.from_numpy(case[k]) for k in ("rx", "tx") if case[k] is not None]
    out = layer(*inputs)
    assert out.dtype == (torch.complex128 if double else torch.complex64)
    assert_close(out, ref[f"beamspace/{name}"], RTOL64 if double else RTOL32, name)


@pytest.fixture(scope="module")
def real_data():
    h = cases.real_channel()
    rx_cb, tx_cb = cases.real_codebooks()
    rx_axis, tx_axis = bf.sionna_mimo_axes("ofdm")
    return h, rx_cb, tx_cb, rx_axis, tx_axis


def check_long(actual, ref, name, stride=32):
    """Compare a long time-domain output through its slice and full-length reductions"""
    a = actual.cpu().numpy()
    assert_close(a[..., ::stride], ref[f"{name}/slice"], RTOL32, f"{name}/slice")
    a128 = a.astype(np.complex128)
    energy = np.sum(np.abs(a128) ** 2, axis=-1)
    total = np.sum(a128, axis=-1)
    # Energy over 2176 samples; reductions accumulate single-precision rounding
    assert_close(energy, ref[f"{name}/energy"], 5e-6, f"{name}/energy")
    assert_close(total, ref[f"{name}/sum"], 5e-6, f"{name}/sum")


def test_real_beamspace(ref, real_data):
    h, rx_cb, tx_cb, rx_axis, tx_axis = real_data
    layer = bf.Beamspace(transmit_axis=tx_axis, receive_axis=rx_axis)
    check_long(layer(torch.from_numpy(h), torch.from_numpy(rx_cb), torch.from_numpy(tx_cb)),
               ref, "real/beamspace_full")
    check_long(layer(torch.from_numpy(h), torch.from_numpy(rx_cb[:, :1]), torch.from_numpy(tx_cb[:, :1])),
               ref, "real/beamspace_siso")


@pytest.mark.parametrize("ortho", [True, False])
@pytest.mark.parametrize("k", [1, 4])
def test_real_beam_selection(ref, real_data, ortho, k):
    h, rx_cb, tx_cb, rx_axis, tx_axis = real_data
    h_tx = bf.Beamspace(transmit_axis=tx_axis)(torch.from_numpy(h), torch.from_numpy(tx_cb))
    check_long(h_tx, ref, "real/beamspace_tx")
    out = bf.BeamSelection(k, orthogonal=ortho, normalize=True)(h_tx)
    check_long(out, ref, f"real/select_{'ortho' if ortho else 'simple'}_k{k}")


def test_top_k_tie_breaking_matches_tensorflow():
    """``torch.topk`` breaks ties differently from ``tf.math.top_k``: lowest index first is required"""
    x = torch.tensor([[1., 3., 3., 3., 0., 3.]])
    assert bf.top_k_indices(x, 3).tolist() == [[1, 2, 3]]


def test_beam_selection_validates_axes():
    h = torch.zeros(2, 2, 2, 2, 8, 2, 2, dtype=torch.complex64)
    with pytest.raises(ValueError):
        bf.BeamSelection(2, beam_axis=2)(h)  # axis 2 is a power axis by default


def test_beam_selection_compile():
    """The block must work under ``torch.compile`` (Sionna convention) and agree with eager mode"""
    case = cases.BEAM_SELECTION_CASES["L30_rand_ortho_k4_norm"]
    h = torch.from_numpy(cases.beam_selection_input(case))
    sel = bf.BeamSelection(**case["kwargs"])
    eager = sel(h)
    try:
        compiled = torch.compile(sel)(h)
    except Exception as e:  # e.g. missing C++ toolchain
        pytest.skip(f"torch.compile unavailable: {type(e).__name__}")
    assert_equal(compiled, eager.numpy())


# ---------------------------------------------------------------------------------------------
# ADC
# ---------------------------------------------------------------------------------------------

def test_complex_max(ref):
    assert_close(adc.complex_max(torch.from_numpy(cases.adc_signal())), ref["adc/complex_max"], RTOL32)


@pytest.mark.parametrize("name", cases.ADC_AXES)
def test_max_abs_complex(ref, name):
    out = adc.max_abs_complex(torch.from_numpy(cases.adc_signal()), **cases.ADC_AXES[name])
    assert_close(out, ref[f"adc/max_abs_complex/{name}"], RTOL32, name)


def mean_sq(sig, kw):
    """Squared magnitude of the mean over the same axes, in NumPy (double precision)"""
    return np.abs(np.mean(sig.astype(np.complex128), axis=kw["axis"], keepdims=kw["keepdims"])) ** 2


@pytest.mark.parametrize("name", cases.ADC_AXES)
def test_signal_power_average_vs_tf_variance(ref, name):
    """
    The average power is E|x|^2 = Var + |E x|^2. The TF ``reduce_variance`` reference is used as oracle:
    the variance is exactly recovered when the squared mean is subtracted from the average power.
    """
    sig, kw = cases.adc_signal(), cases.ADC_AXES[name]
    power = signal_power(torch.from_numpy(sig), average=True, **kw).numpy().astype(np.float64)
    var_tf = ref[f"adc/variance/{name}"].astype(np.float64)
    assert_close((power - mean_sq(sig, kw)).astype(np.float32), var_tf.astype(np.float32), 1e-5, name)


@pytest.mark.parametrize("name", cases.ADC_AXES)
def test_signal_power_identities(name):
    sig, kw = cases.adc_signal(), cases.ADC_AXES[name]
    t = torch.from_numpy(sig)
    num_elements = np.prod([sig.shape[a] for a in axes_tuple(kw["axis"], sig.ndim)])

    # The default is a sum, the average is the sum divided by the number of aggregated elements
    total = signal_power(t, **kw).numpy()
    average = signal_power(t, average=True, **kw).numpy()
    np.testing.assert_allclose(total, average * num_elements, rtol=1e-5)

    # Real signals
    real = sig.real
    np.testing.assert_allclose(signal_power(torch.from_numpy(real), average=True, **kw).numpy(),
                               np.mean(real ** 2, axis=kw["axis"], keepdims=kw["keepdims"]), rtol=1e-5)

    # For zero-mean signals, the average power is the (population) variance
    zero_mean = sig - np.mean(sig, axis=kw["axis"], keepdims=True)
    np.testing.assert_allclose(signal_power(torch.from_numpy(zero_mean), average=True, **kw).numpy(),
                               np.var(zero_mean, axis=kw["axis"], keepdims=kw["keepdims"]), rtol=1e-5)


@pytest.mark.parametrize("name", cases.ADC_AXES)
def test_papr(ref, name):
    """
    PAPR is referred to the average power instead of the variance (which discards the mean).
    The TF reference is converted accordingly: papr = max|x|^2 / (Var + |E x|^2)
    """
    sig, kw = cases.adc_signal(), cases.ADC_AXES[name]
    var_tf = ref[f"adc/variance/{name}"].astype(np.float64)
    expected = ref[f"adc/papr/{name}"].astype(np.float64) * var_tf / (var_tf + mean_sq(sig, kw))
    out = adc.papr(torch.from_numpy(sig), **kw)
    assert_close(out, expected.astype(np.float32), 2e-5, name)


@pytest.mark.parametrize("bits", cases.ADC_BITS)
def test_quantize_signal(ref, bits):
    sig = torch.from_numpy(cases.adc_signal())
    assert_close(adc.quantize_signal(sig, bits), ref[f"adc/quantize/{bits}/auto"], RTOL32, "auto")
    assert_close(adc.quantize_signal(sig, bits, max_value=4.0), ref[f"adc/quantize/{bits}/fixed"], RTOL32, "fixed")


# ---------------------------------------------------------------------------------------------
# raytracing
# ---------------------------------------------------------------------------------------------

def test_save_si_matrix(ref, tmp_path):
    ht_si, t_channel_s = cases.real_si_data()
    fname = tmp_path/"si_mimo.npz"
    t_si = rtr.save_si_matrix(torch.from_numpy(ht_si), t_channel_s, fname=fname)
    with np.load(fname) as d:
        # The selected taps are copied, so they must be exactly equal
        assert_equal(d["h_si_matrix"], ref["rtr/si_matrix/h_si_matrix"], "h_si_matrix")
        assert_close(d["mean_delay"], ref["rtr/si_matrix/mean_delay"], 1e-6, "mean_delay")
    assert_close(t_si, ref["rtr/si_matrix/returned"], 1e-6, "returned delay")


def test_load_cir():
    fname = cases.FIXTURE_PATH
    t_rt = rtr.load_cir("t_channel_s", fname=fname, torch_type=None)
    assert isinstance(t_rt, np.ndarray)
    ht_tgt, ht_si = rtr.load_cir("ht_tgt", "ht_si", fname=fname)
    assert ht_tgt.dtype == torch.complex64 and ht_si.dtype == torch.complex64
    with np.load(fname) as d:
        assert_equal(ht_si, d["ht_si"])
        assert_equal(ht_tgt, d["ht_tgt"])


def test_save_cir_roundtrip(tmp_path):
    """Tensors (any device) and arrays are stored as plain NumPy arrays"""
    ht_si = cases.rand_complex((2, 1, 4, 1, 4, 1, 16), seed=700)
    ht_tgt = cases.rand_complex((3, 1, 4, 1, 4, 1, 16), seed=701)
    t = np.arange(16) * 5e-10
    for convert in (torch.from_numpy, np.asarray):
        fname = tmp_path/"cir.npz"
        rtr.save_cir(convert(ht_si), convert(ht_tgt), t, fname=fname)
        loaded_si, loaded_tgt, loaded_t = rtr.load_data("ht_si", "ht_tgt", "t_channel_s", fname=fname)
        assert_equal(loaded_si, ht_si)
        assert_equal(loaded_tgt, ht_tgt)
        assert_equal(loaded_t, t)
