name: Apptainer Build Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    paths:
      - "**.def"
      - "**.sh"
      - "**.yml"
      - "**/requirements.txt"

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: quay.io/singularity/singularity:v4.1.0
        options: --privileged

    name: Build Container
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "Repository name: ${{github.repository}}"
          echo "Repository owner: ${{github.repository_owner}}"
          echo "Tag name: ${{github.ref_name}}"

      - name: Build Container
        run: |
           singularity build cluster/sionna.sif cluster/sionna.def

      - name: Login and Deploy Container
        run: |
           echo ${{ secrets.GITHUB_TOKEN }} | singularity registry login -u ${{github.repository_owner}} --password-stdin oras://ghcr.io
           singularity push cluster/sionna.sif oras://ghcr.io/${{github.repository}}:${{github.ref_name}}
